global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'furniture-store'
    static_configs:
      - targets: ['furniture-store:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s