apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: furniture-store-uploads-pvc
  namespace: furniture-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: furniture-store-db-pvc
  namespace: furniture-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi