apiVersion: v1
kind: Secret
metadata:
  name: furniture-store-secrets
  namespace: furniture-store
type: Opaque
data:
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ== # base64 encoded
  SMTP_USER: c210cC11c2Vy # base64 encoded
  SMTP_PASS: c210cF9wYXNz # base64 encoded
  STRIPE_SECRET_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5 # base64 encoded